# GolangCI-Lint Configuration
# TelemetryFlow Agent - Community Enterprise Observability Platform (CEOP)

run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - staticcheck
    - govet
    - errcheck
    - ineffassign
    - unused

issues:
  exclude-dirs:
    - vendor
  exclude-files:
    - internal/collector/ebpf/types.go
    - internal/collector/ebpf/helpers.go
    - internal/collector/ebpf/hubble.go
  exclude-rules:
    - path: internal/collector/ebpf/config.go
      linters:
        - unused
      text: "shouldIncludeProcess"

linters-settings:
  staticcheck:
    checks:
      - "all"
      - "-SA1019"
