apiVersion: v2
name: tfo-agent
description: TelemetryFlow Agent - Kubernetes observability and node metrics collector
type: application
version: 0.1.0
appVersion: "1.2.0"
keywords:
  - observability
  - monitoring
  - kubernetes
  - telemetry
  - metrics
home: https://telemetryflow.io
sources:
  - https://github.com/telemetryflow/telemetryflow-agent
maintainers:
  - name: TelemetryFlow Team
    email: support@telemetryflow.id
