{{- if .Values.kubernetesCollector.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tfo-agent.k8sConfigMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tfo-agent.labels" . | nindent 4 }}
data:
  tfo-agent.yaml: |
    {{- if .Values.oneForAll.enabled }}
    one_for_all:
      enabled: true
    {{- end }}
    {{- toYaml .Values.kubernetes.config | nindent 4 }}
{{- end }}
