// Package fluentbit embeds Fluent Bit as a managed subprocess log collector.
//
// parsers.go contains built-in Fluent Bit parser and multiline parser definitions
// for Docker JSON, CRI, syslog, and common multiline stack trace patterns.
//
// TelemetryFlow Agent - Community Enterprise Observability Platform
// Copyright (c) 2024-2026 TelemetryFlow. All rights reserved.
// Open Source Software built by DevOpsCorner Indonesia.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
package fluentbit

// BuiltinParsersConf contains standard parser definitions for common log formats.
const BuiltinParsersConf = `# TelemetryFlow Agent — built-in Fluent Bit parsers
# Auto-generated by TFO-Agent. Do not edit manually.

[PARSER]
    Name        docker
    Format      json
    Time_Key    time
    Time_Format %Y-%m-%dT%H:%M:%S.%L
    Time_Keep   On

[PARSER]
    Name        cri
    Format      regex
    Regex       ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
    Time_Key    time
    Time_Format %Y-%m-%dT%H:%M:%S.%L%z
    Time_Keep   On

[PARSER]
    Name        syslog-rfc5424
    Format      regex
    Regex       ^\<(?<pri>[0-9]{1,5})\>1 (?<time>[^ ]+) (?<host>[^ ]+) (?<ident>[^ ]+) (?<pid>[-0-9]+) (?<msgid>[^ ]+) (?<extradata>(\[(.*?)\]|-)+) (?<message>.+)$
    Time_Key    time
    Time_Format %Y-%m-%dT%H:%M:%S.%L%z

[PARSER]
    Name        syslog-rfc3164
    Format      regex
    Regex       /^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$/
    Time_Key    time
    Time_Format %b %d %H:%M:%S

[PARSER]
    Name        json
    Format      json
    Time_Key    time
    Time_Format %Y-%m-%dT%H:%M:%S.%L
    Time_Keep   On
`

// BuiltinMultilineParsersConf contains multiline parser definitions for common stack traces.
const BuiltinMultilineParsersConf = `# TelemetryFlow Agent — multiline parsers
# Auto-generated by TFO-Agent. Do not edit manually.

[MULTILINE_PARSER]
    name          java-stacktrace
    type          regex
    flush_timeout 1000
    # Start of a Java exception/stack trace
    rule          "start_state"  "/^(\d{4}-\d{2}-\d{2}|[A-Z][a-z]{2}\s|Exception|Caused by|com\.|org\.|java\.|javax\.)/"  "cont"
    rule          "cont"         "/^\s+(at |\.{3}\s|Caused by|java\.|javax\.|com\.|org\.)/"                                 "cont"

[MULTILINE_PARSER]
    name          python-traceback
    type          regex
    flush_timeout 1000
    rule          "start_state"  "/^Traceback \(most recent call last\):$/"  "cont"
    rule          "cont"         "/^\s+File /"                                "cont"
    rule          "cont"         "/^\s+/"                                     "cont"
    rule          "cont"         "/^\S+Error:/"                               "cont"

[MULTILINE_PARSER]
    name          go-panic
    type          regex
    flush_timeout 1000
    rule          "start_state"  "/^(panic:|goroutine \d+|runtime error:)/"  "cont"
    rule          "cont"         "/^\s+/"                                     "cont"
    rule          "cont"         "/^goroutine \d+/"                           "cont"
`
